import React, { useState, useEffect } from 'react';
import { User, Article } from '../types';
import { Button, Card, Badge } from './ui';
import { ArrowLeft, User as UserIcon, Shield, Trash2, LogOut, RefreshCw, Plus, Save, X, Newspaper, Users } from 'lucide-react';
import { knowledgeBase } from '../services/knowledgeBase';

interface SettingsProps {
    user: User;
    onBack: () => void;
    onLogout: () => void;
    onResetProgress: () => void;
}

export const Settings: React.FC<SettingsProps> = ({ user, onBack, onLogout, onResetProgress }) => {
    const [activeTab, setActiveTab] = useState<'PROFILE' | 'ADMIN'>('PROFILE');
    const [articles, setArticles] = useState<Article[]>([]);

    // Admin State
    const [isCreatingArticle, setIsCreatingArticle] = useState(false);
    const [newArticle, setNewArticle] = useState<Partial<Article>>({
        category: 'Filosofia',
        readTime: '3 min',
        content: []
    });
    const [contentInput, setContentInput] = useState('');

    useEffect(() => {
        if (activeTab === 'ADMIN') {
            loadArticles();
        }
    }, [activeTab]);

    const loadArticles = async () => {
        const data = await knowledgeBase.getAllArticles();
        setArticles(data);
    };

    const handleDeleteArticle = async (id: string) => {
        if (window.confirm('Tem certeza que deseja apagar este artigo permanentemente?')) {
            await knowledgeBase.deleteArticle(id);
            loadArticles();
        }
    };

    const handleCreateArticle = async () => {
        if (!newArticle.title || !contentInput) return;

        const paragraphs = contentInput.split('\n').filter(p => p.trim());

        // Note: ID generated by DB
        const article: any = {
            title: newArticle.title!,
            category: newArticle.category as any,
            readTime: newArticle.readTime || '3 min',
            author: newArticle.author || 'Equipe YogaFlow',
            imageUrl: newArticle.imageUrl || null,
            excerpt: paragraphs[0]?.slice(0, 150) + '...',
            content: paragraphs,
            isUserGenerated: false // Oficial
        };

        await knowledgeBase.addArticle(article);
        setIsCreatingArticle(false);
        setNewArticle({ category: 'Filosofia', readTime: '3 min', author: 'Equipe YogaFlow' });
        setContentInput('');
        loadArticles();
    };

    return (
        <div className="bg-stone-50 min-h-screen px-4 pt-2 pb-24 animate-fade-in">
            {/* Header */}
            <div className="max-w-3xl mx-auto mb-2 flex items-center gap-3 pt-2">
                <Button variant="ghost" onClick={onBack} className="text-stone-600 hover:bg-stone-200 -ml-2 h-10 w-10 p-0 rounded-full">
                    <ArrowLeft size={24} />
                </Button>
                <h1 className="text-2xl font-serif text-stone-800 font-medium">Configurações</h1>
            </div>

            <div className="max-w-3xl mx-auto space-y-6">
                {/* Tabs UI - Only for Admin (regular users see Profile directly) */}
                {user.isAdmin && (
                    <div className="flex bg-stone-200/50 p-1 rounded-xl w-fit mb-6">
                        <button
                            onClick={() => setActiveTab('PROFILE')}
                            className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all ${activeTab === 'PROFILE' ? 'bg-white shadow-sm text-sage-800' : 'text-stone-500 hover:text-stone-700'}`}
                        >
                            <UserIcon size={16} /> Perfil
                        </button>
                        <button
                            onClick={() => setActiveTab('ADMIN')}
                            className={`flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition-all ${activeTab === 'ADMIN' ? 'bg-white shadow-sm text-sage-800' : 'text-stone-500 hover:text-stone-700'}`}
                        >
                            <Shield size={16} /> Admin
                        </button>
                    </div>
                )}

                {/* Content Area */}
                <div className="animate-fade-in">
                    {activeTab === 'PROFILE' && (
                        <div className="space-y-6">
                            <Card className="p-6">
                                <h2 className="text-xl font-serif text-stone-800 mb-6">Suas Informações</h2>
                                <div className="flex items-center gap-4 mb-6">
                                    <div className="w-16 h-16 rounded-full bg-sage-200 flex items-center justify-center text-sage-800 text-2xl font-bold">
                                        {user.name.charAt(0)}
                                    </div>
                                    <div>
                                        <p className="font-bold text-lg text-stone-800">{user.name}</p>
                                        <p className="text-stone-500">{user.email}</p>
                                        {user.isAdmin && <Badge color="purple" className="mt-2">Administrador</Badge>}
                                    </div>
                                </div>
                                <Button variant="outline" onClick={onLogout} className="w-full text-red-500 hover:bg-red-50 border-red-200 justify-center">
                                    <LogOut size={18} className="mr-2" /> Sair da Conta
                                </Button>
                            </Card>

                            <Card className="p-6">
                                <h2 className="text-xl font-serif text-stone-800 mb-6">Dados & Progresso</h2>
                                <p className="text-stone-600 mb-4 text-sm">
                                    Esta ação irá limpar suas preferências locais, histórico de treinos e redefinir o onboarding.
                                    Sua conta será mantida.
                                </p>
                                <Button onClick={onResetProgress} className="w-full bg-stone-100 text-stone-600 hover:bg-stone-200 hover:text-red-600 justify-center border border-stone-200">
                                    <RefreshCw size={18} className="mr-2" /> Resetar Todo o Progresso
                                </Button>
                            </Card>
                        </div>
                    )}

                    {activeTab === 'ADMIN' && user.isAdmin && (
                        <div className="space-y-6">
                            <Card className="p-6">
                                <div className="flex items-center justify-between mb-6">
                                    <h2 className="text-xl font-serif text-stone-800">Gerenciar Conteúdo</h2>
                                    <Button onClick={() => setIsCreatingArticle(true)} className="bg-sage-600 text-white hover:bg-sage-700">
                                        <Plus size={18} className="mr-2" /> Novo Artigo Oficial
                                    </Button>
                                </div>

                                {isCreatingArticle && (
                                    <div className="mb-8 p-6 bg-stone-50 rounded-xl border border-stone-200 animate-fade-in shadow-inner">
                                        <div className="flex justify-between mb-4">
                                            <h3 className="font-bold text-stone-700">Novo Artigo</h3>
                                            <button onClick={() => setIsCreatingArticle(false)}><X size={20} className="text-stone-400 hover:text-stone-600" /></button>
                                        </div>
                                        <div className="space-y-4">
                                            <input
                                                className="w-full p-3 border border-stone-200 rounded-lg focus:ring-2 focus:ring-sage-200 outline-none"
                                                placeholder="Título do Artigo"
                                                value={newArticle.title || ''}
                                                onChange={e => setNewArticle({ ...newArticle, title: e.target.value })}
                                            />
                                            <div className="grid grid-cols-2 gap-4">
                                                <select
                                                    className="p-3 border border-stone-200 rounded-lg focus:ring-2 focus:ring-sage-200 outline-none bg-white"
                                                    value={newArticle.category}
                                                    onChange={e => setNewArticle({ ...newArticle, category: e.target.value as any })}
                                                >
                                                    <option>Filosofia</option>
                                                    <option>Benefícios</option>
                                                    <option>Inspiração</option>
                                                    <option>Anatomia</option>
                                                </select>
                                                <input
                                                    className="p-3 border border-stone-200 rounded-lg focus:ring-2 focus:ring-sage-200 outline-none"
                                                    placeholder="Autor (ex: Equipe YogaFlow)"
                                                    value={newArticle.author || ''}
                                                    onChange={e => setNewArticle({ ...newArticle, author: e.target.value })}
                                                />
                                            </div>
                                            <input
                                                className="w-full p-3 border border-stone-200 rounded-lg focus:ring-2 focus:ring-sage-200 outline-none"
                                                placeholder="URL da Imagem (Unsplash)"
                                                value={newArticle.imageUrl || ''}
                                                onChange={e => setNewArticle({ ...newArticle, imageUrl: e.target.value })}
                                            />
                                            <textarea
                                                className="w-full p-3 border border-stone-200 rounded-lg min-h-[150px] focus:ring-2 focus:ring-sage-200 outline-none resize-y"
                                                placeholder="Conteúdo (parágrafos separados por enter)"
                                                value={contentInput}
                                                onChange={e => setContentInput(e.target.value)}
                                            />
                                            <Button onClick={handleCreateArticle} disabled={!newArticle.title || !contentInput} className="w-full bg-sage-600 text-white hover:bg-sage-700 disabled:opacity-50">
                                                <Save size={18} className="mr-2" /> Publicar Artigo
                                            </Button>
                                        </div>
                                    </div>
                                )}

                                <div className="space-y-3">
                                    {articles.map(article => (
                                        <div key={article.id} className="flex items-center justify-between p-4 bg-white border border-stone-100 rounded-xl hover:shadow-md transition-shadow">
                                            <div className="flex items-center gap-4">
                                                <div className={`p-2 rounded-lg ${article.isUserGenerated ? 'bg-purple-100 text-purple-600' : 'bg-blue-100 text-blue-600'}`}>
                                                    {article.isUserGenerated ? <Users size={20} /> : <Newspaper size={20} />}
                                                </div>
                                                <div>
                                                    <p className="font-bold text-stone-800 line-clamp-1">{article.title}</p>
                                                    <p className="text-xs text-stone-500">
                                                        {article.author} • {article.likes} likes • {article.comments?.length || 0} comments
                                                        {article.isUserGenerated && <span className="ml-2 font-bold text-purple-600">Comunidade</span>}
                                                    </p>
                                                </div>
                                            </div>
                                            <button
                                                onClick={() => handleDeleteArticle(article.id)}
                                                className="text-stone-400 hover:text-red-500 hover:bg-red-50 p-2 rounded-full transition-colors"
                                                title="Apagar Publicação"
                                            >
                                                <Trash2 size={20} />
                                            </button>
                                        </div>
                                    ))}
                                    {articles.length === 0 && <p className="text-center text-stone-500 py-8">Nenhum artigo encontrado.</p>}
                                </div>
                            </Card>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
};
